server:
    port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-cpj5enuct0pc738494vg-a.oregon-postgres.render.com:5432/cyberhunter_8guf
    username: cyberhunter_8guf_user
    password: fvXa9Pg1kfCGn8FtRVCsn9bRW33FPjw7
    driver-class-name: org.postgresql.Driver
    initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres